name: Release Drafter Autolabler
on:
    pull_request:
      types: [opened, synchronize, reopened, edited]

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: "0"
            
      # Set up Release Drafter
      - name: Release Drafter
        id: release
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: false
          config-name: release_drafter.yml
          publish: false
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    