name: Release Drafter

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Matches tags like v1.0.0, v2.1.3
  
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: "0"
      
      - name: Get Tag Name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      # Set up Release Drafter
      - name: Release Drafter
        id: release
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: false
          config-name: release_drafter.yml
          draft: false
          publish: true
          commitish: main
          name: ${{ env.TAG_NAME }}
          tag: ${{ env.TAG_NAME }}
          version: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    