name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  update_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Semver
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Process new_tag 
        id: process_new_tag
        run: |
              echo "new_tag=${{steps.semver.outputs.next}}" >> $GITHUB_ENV      - name: Create Release

  update_release_draft:
    if: false
    permissions:
      contents: write
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: "0"

      # Set up Release Drafter
      - name: Release Drafter
        id: release
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: false
          config-name: release_drafter.yml
          commitish: main
          name: next
          tag: next
          version: next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
      - name: Process new_tag 
        id: process_new_tag
        run: |
            echo "new_tag=${{steps.release.outputs.tag_name}}" >> $GITHUB_ENV