name: Release Drafter
on:
    workflow_run:
      workflows: ["Version and tag"]  # This name should match the first workflow
      types:
        - completed
      
permissions:
  contents: write

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: "0"
      
      - name: Get Tag Name
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      
      # Set up Release Drafter
      - name: Release Drafter
        id: release
        uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
          config-name: release_drafter.yml
          publish: true
          commitish: main
          name: ${{ env.TAG }}
          tag: ${{ env.TAG }}
          version: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    