on:
    push:
      branches:
        - main
jobs:
  update_tag:
    permissions:
      contents: write
      pull-requests: write
      checks: write
    
    runs-on: ubuntu-latest
    steps:      
      - name: Semver
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main


      - name: Create and push tag
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git tag ${{steps.semver.outputs.next}}
            git push origin ${{steps.semver.outputs.next}}

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{steps.semver.outputs.next}}',
                sha: context.sha
              })  
          token: ${{ secrets.GITHUB_TOKEN }}        
