on:
    push:
      branches:
        - main
jobs:
  update_tag:
    runs-on: ubuntu-latest
    steps:      
      - name: Semver
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Create and push tag
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git tag ${{steps.semver.outputs.next}}
            git push origin ${{steps.semver.outputs.next}}
