on:
    push:
      branches:
        - main
jobs:
  update_tag:
    permissions:
      contents: write
      pull-requests: write
      checks: write
    
    runs-on: ubuntu-latest
    steps:      
      - name: Semver
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{steps.semver.outputs.next}}',
                sha: context.sha
              })  
      
